[build.environment]
  NODE_VERSION = "16.x"
  NODE_OPTIONS = "--openssl-legacy-provider"
[build]
  base = "/"
  publish = "public/"
  command = "npm run build"
  functions = "functions/"
[dev]
  publish = "public"
